### PR TITLE
Add loop for deploying to mutiple envs

### PR DESCRIPTION
**Pull request by grasbergerm**

### CODE REVIEW

**Comment by imperfect-ed** [comment]
LGTM

**Comment by bardito-imperfect** [comment]
This LGTM except I don't understand the context in which we would be deploying to multiple envs in one go.  Can you explain the situation this would be used in please?

**Comment by grasbergerm** [comment]
> This LGTM except I don't understand the context in which we would be deploying to multiple envs in one go. Can you explain the situation this would be used in please?

This change is to deploy to dev and staging environments on merge to master.

**Comment by grasbergerm** [comment]
> I'm concerned that this is a breaking change, and that the `EB_ENV_NAME` will no longer be honored. Keep in mind that this is a public repo which has a half decent number of followers and forks. Can we make this backwards compatible some how? Perhaps keep `EB_ENV_NAME` variable name but support some convention for optionally delimiting multiple environments within that variable.

Good call, I didn't realize that, thanks Stephen. I'll make sure this is backwards compatible with EB_ENV_NAME

**Comment by grasbergerm** [comment]
Tested here, https://app.circleci.com/pipelines/github/imperfectproduce/atp-v2/31/workflows/ee7c8dd3-9945-4807-a0ad-5c54d59e1a37
atp v2 branch for testing deploy update: https://github.com/imperfectproduce/atp-v2/blob/a963aeac0fe6cad7face946a55923f658ec4f7ef/deploy.sh

**Pull request merged**
